#pragma once

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

namespace agentsdk::a2a
{

/**
 * Task states as defined by A2A 1.0.
 *
 * Terminal states: completed, failed, canceled, rejected.
 * Interrupted states: input_required, auth_required.
 */
enum class task_state
{
  unspecified,
  submitted,
  working,
  completed,
  failed,
  canceled,
  input_required,
  rejected,
  auth_required
};

/**
 * Returns ``true`` if the given state is terminal.
 */
bool is_terminal (task_state state);

/**
 * Returns ``true`` if the given state is an interrupted state.
 */
bool is_interrupted (task_state state);

/**
 * Message role.
 */
enum class role
{
  unspecified,
  user,
  agent
};

/**
 * The smallest unit of content within a message or artifact.
 *
 * A part contains exactly one of: text, raw bytes, a URL, or structured data.
 * In JSON the active variant is determined by which field is present
 * (``text``, ``raw``, ``url``, ``data``) -- there is no ``kind`` discriminator.
 */
struct part
{
  /** Text content. */
  std::optional<std::string> text;
  /** Raw file bytes, base64-encoded in JSON. */
  std::optional<std::string> raw;
  /** URL pointing to file content. */
  std::optional<std::string> url;
  /** Arbitrary structured JSON data, stored as a raw JSON string. */
  std::optional<std::string> data;
  /** Optional metadata, stored as a raw JSON string. */
  std::optional<std::string> metadata;
  /** Optional file name (for file parts). */
  std::optional<std::string> filename;
  /** MIME type (e.g. "text/plain", "image/png"). */
  std::optional<std::string> media_type;
};

/**
 * A communication turn between a client and a remote agent.
 *
 * Messages are used to initiate tasks, request clarification, and
 * provide additional input. They should not be used to deliver task
 * outputs -- use artifacts for that.
 */
struct message
{
  /** UUID, creator-generated. */
  std::string message_id;
  /** Optional context association. */
  std::optional<std::string> context_id;
  /** Optional task association. */
  std::optional<std::string> task_id;
  /** Message role (user or agent). */
  agentsdk::a2a::role role;
  /** Message content parts. At least one required. */
  std::vector<part> parts;
  /** Optional metadata as a raw JSON string. */
  std::optional<std::string> metadata;
  /** Extension URIs present on this message. */
  std::vector<std::string> extensions;
  /** Referenced task IDs for context. */
  std::vector<std::string> reference_task_ids;
};

/**
 * Current status of a task, including its state and optional status message.
 */
struct task_status
{
  /** Current task state. */
  task_state state = task_state::unspecified;
  /** Optional status message from the agent. */
  std::optional<message> status_message;
  /** ISO 8601 UTC timestamp of the last state change. */
  std::optional<std::string> timestamp;
};

/**
 * An output generated by the agent as a result of a task.
 *
 * Artifacts contain the actual deliverables (documents, images, structured
 * data) as opposed to status messages.
 */
struct artifact
{
  /** UUID, unique within a task. */
  std::string artifact_id;
  /** Human-readable name. */
  std::optional<std::string> name;
  /** Human-readable description. */
  std::optional<std::string> description;
  /** Artifact content parts. At least one required. */
  std::vector<part> parts;
  /** Optional metadata as a raw JSON string. */
  std::optional<std::string> metadata;
  /** Extension URIs. */
  std::vector<std::string> extensions;
};

/**
 * The fundamental unit of work managed by A2A.
 *
 * Tasks are stateful and progress through a defined lifecycle from
 * submitted to a terminal state.
 */
struct task
{
  /** Server-generated UUID. */
  std::string id;
  /** Groups related tasks and messages. */
  std::optional<std::string> context_id;
  /** Current task status. */
  task_status status;
  /** Output artifacts produced by the agent. */
  std::vector<artifact> artifacts;
  /** Interaction history (may be incomplete). */
  std::vector<message> history;
  /** Optional metadata as a raw JSON string. */
  std::optional<std::string> metadata;
};

/**
 * Streaming event for task status changes.
 */
struct task_status_update_event
{
  /** Task ID this event belongs to. */
  std::string task_id;
  /** Context ID. */
  std::string context_id;
  /** Updated status. */
  task_status status;
  /** Optional metadata as a raw JSON string. */
  std::optional<std::string> metadata;
};

/**
 * Streaming event for artifact creation or updates.
 */
struct task_artifact_update_event
{
  /** Task ID this event belongs to. */
  std::string task_id;
  /** Context ID. */
  std::string context_id;
  /** The generated or updated artifact. */
  artifact artifact_data;
  /** If ``true``, append to the previous artifact with the same ID. */
  bool append = false;
  /** If ``true``, this is the final chunk for this artifact. */
  bool last_chunk = false;
  /** Optional metadata as a raw JSON string. */
  std::optional<std::string> metadata;
};

/**
 * Wrapper for all streaming payloads.
 *
 * Exactly one field is active in each instance.
 */
struct stream_response
{
  /** Current task state. */
  std::optional<task> task_payload;
  /** Agent message. */
  std::optional<message> message_payload;
  /** Status change event. */
  std::optional<task_status_update_event> status_update;
  /** Artifact update event. */
  std::optional<task_artifact_update_event> artifact_update;
};

/**
 * Optional integer parameter (absent means "use server default").
 */
struct optional_int32
{
  std::optional<int32_t> value;
};

} // namespace agentsdk::a2a
